=== mshulgina/CTT-Project/WSDL/task3/Transaction-Details.xsd
<!-- edited with XMLSpy v2014 rel. 2 sp1 (x64) (http://www.altova.com) by CINIMEX INFORMATICA (CINIMEX INFORMATICA) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Transaction-Details">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Transaction-ID" type="xs:string">
					<xs:annotation>
						<xs:documentation>ID транзакции</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Deal-Type" type="xs:string">
					<xs:annotation>
						<xs:documentation>Тип сделки (константа)</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="TimeStamp" type="xs:dateTime">
					<xs:annotation>
						<xs:documentation>Time Stamp</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Payer-Name" type="xs:string">
					<xs:annotation>
						<xs:documentation>Имя плательшика</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Payer-Account" type="CBAcc">
					<xs:annotation>
						<xs:documentation>Счет плательшика</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Beneficiary-Name" type="xs:string">
					<xs:annotation>
						<xs:documentation>Имя получателя</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Beneficiary-Account" type="CBAcc">
					<xs:annotation>
						<xs:documentation>Счет получателя</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Deal-Amount" type="AmountFormat">
					<xs:annotation>
						<xs:documentation>Сумма перевода</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Deal-Date" type="xs:date">
					<xs:annotation>
						<xs:documentation>Дата сделки</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="Deal-Currecny" type="CurCode">
					<xs:annotation>
						<xs:documentation>Валюта</xs:documentation>
					</xs:annotation>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:simpleType name="CurCode">
		<xs:annotation>
			<xs:documentation>Формат кода валюты</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:minLength value="3"/>
			<xs:maxLength value="3"/>
			<xs:pattern value="[A-Z]{3}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="CBAcc">
		<xs:annotation>
			<xs:documentation>Формат счета ЦБ</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="([0-9]){20}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="AmountFormat">
		<xs:annotation>
			<xs:documentation>Формат суммы перевода</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="([0-9]{1,})\.([0-9]{2})"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>

=== mshulgina/CTT-Project/Templates/task3/ex3_out_response_msg_1.xml
<Transaction-Details xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Transaction-Details.xsd">
	<Transaction-ID>3216736241235</Transaction-ID>
	<Deal-Type>mpayment</Deal-Type>
	<TimeStamp>2016-02-04T09:47:14Z</TimeStamp>
	<Payer-Name>Parhomenko Aleksey Karlovich</Payer-Name>
	<Payer-Account>44198001679010034901</Payer-Account>
	<Beneficiary-Name>Medvedev Boris Vladimirovoch</Beneficiary-Name>
	<Beneficiary-Account>44197671167183327082</Beneficiary-Account>
	<Deal-Amount>10000.99</Deal-Amount>
	<Deal-Date>2016-01-13</Deal-Date>
	<Deal-Currecny>BCZ</Deal-Currecny>
</Transaction-Details>
